[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.module]
source = "lovely/label.lua"
before = "game.lua"
name = "bus693sweetshop"

# Insert module dependency at the top
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "Game = Object:extend()"
position = "before"
payload = '''
local __bus693sweetshop = require('bus693sweetshop')
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "definition = create_UIBox_HUD(),"
position = "at"
payload = '''
definition = __bus693sweetshop.add_label(create_UIBox_HUD()),
'''
match_indent = true
times = 1